// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upggygnqbznefccekanv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZ2d5Z25xYnpuZWZjY2VrYW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDQyMDUsImV4cCI6MjA3MjYyMDIwNX0.OykEtUzNIpGrbWHosBux_N9kmKLGD8ccNAmXfFMhDL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});